# Generated by Django 4.0 on 2021-12-14 22:41
from django.core.management.sql import emit_post_migrate_signal


from django.db import migrations


def create_groups(apps, schema_migration):
    emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

    User = apps.get_model('bugtracker', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    def get_permissions(model_name):
        add = Permission.objects.get(codename=f'add_{model_name}')
        change = Permission.objects.get(codename=f'change_{model_name}')
        delete = Permission.objects.get(codename=f'delete_{model_name}')
        view = Permission.objects.get(codename=f'view_{model_name}')
        return [add, change, delete, view]

    admin = Group(name='admins')
    project_manager = Group(name='project managers')
    submitter = Group(name='submitters')
    developer = Group(name='developers')

    admin.save()
    project_manager.save()
    submitter.save()
    developer.save()

    ticket_permissions = get_permissions('ticket')

    print('ticket perms ', ticket_permissions)

    admin.permissions.add(*ticket_permissions)
    project_manager.permissions.add(*ticket_permissions)
    submitter.permissions.add(*ticket_permissions)
    developer.permissions.add(*ticket_permissions)

    for user in User.objects.all():
        if user.role == 'ADMIN':
            admin.user_set.add(user)
        elif user.role == 'PROJECT_MANAGER':
            project_manager.user_set.add(user)
        elif user.role == 'DEVELOPER':
            developer.user_set.add(user)
        elif user.role == 'SUBMITTER':
            submitter.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
