# Generated by Django 4.0 on 2021-12-18 20:29

from django.db import migrations

from django.core.management.sql import emit_post_migrate_signal


def create_groups(apps, schema_migration):
    emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

    User = apps.get_model('bugtracker', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    def get_permissions(model_name):
        add = Permission.objects.get(codename=f'add_{model_name}')
        change = Permission.objects.get(codename=f'change_{model_name}')
        delete = Permission.objects.get(codename=f'delete_{model_name}')
        view = Permission.objects.get(codename=f'view_{model_name}')
        return [view, add, change, delete]

    admin = Group(name='admins')
    project_manager = Group(name='project managers')
    submitter = Group(name='submitters')
    developer = Group(name='developers')

    admin.save()
    project_manager.save()
    submitter.save()
    developer.save()

    role_change = Permission.objects.get(codename="change_role")

    ticket_permissions = get_permissions('ticket')
    project_permissions = get_permissions('project')

    admin.permissions.add(*ticket_permissions, *
                          project_permissions, role_change)
    project_manager.permissions.add(*ticket_permissions, *project_permissions)
    developer.permissions.add(*ticket_permissions, project_permissions[0])
    submitter.permissions.add(
        ticket_permissions[0], ticket_permissions[1], project_permissions[0])

    for user in User.objects.all():
        if user.role == 'ADMIN':
            admin.user_set.add(user)
        elif user.role == 'PROJECT_MANAGER':
            project_manager.user_set.add(user)
        elif user.role == 'DEVELOPER':
            developer.user_set.add(user)
        elif user.role == 'SUBMITTER':
            submitter.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
