# Generated by Django 4.0 on 2021-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20211214_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('SUBMITTER', 'Submitter'), ('DEVELOPER', 'Developer')], max_length=32),
        ),
    ]
