# Generated by Django 4.0 on 2021-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20211218_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
