# Generated by Django 4.0 on 2021-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Resolved', 'Resolved'), ('Additional Info Required', 'Additional Info Required')], default='New', max_length=32),
        ),
    ]
